name: Web Scraping and Notification

on:
  schedule:
    - cron: "* 1 * * *" 

jobs:
  scrape_and_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Run the scraper and generator # name后面的是当前任务的描述, 不需要管
        run: node scraper.js # 替换为您的爬虫脚本的文件名

      - name: Build
        run: yarn docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
          publish_branch: gh-pages

      - name: Show Deployed URL
        run: |
          echo "Deployed Website URL: https://lzdml.github.io/high-star/"

      - name: Send email notification
        run: npm run start # 替换为发送邮件的脚本命令或代码
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_SEND_TO: ${{ secrets.SMTP_SEND_TO }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
